name = "psychopomp"
version = "0.1.0"
defaultTargets = ["Psychopomp"]
testDriver = "testPsychopomp"

[[require]]
name = "kenosis"
git = "https://github.com/SrGaabriel/kenosis"
rev = "main"

[[lean_lib]]
name = "Psychopomp"

[[lean_lib]]
name = "PsychopompTest"

[[lean_exe]]
name = "testPsychopomp"
root = "Test"
